# Generated by Django 6.0.2 on 2026-02-26 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WepApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(blank=True, max_length=100, null=True)),
                ('Email', models.EmailField(blank=True, max_length=254, null=True)),
                ('Password', models.CharField(blank=True, max_length=100, null=True)),
                ('Confrom_Password', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
