# Generated by Django 6.0.2 on 2026-02-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WepApp', '0002_accountdb'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=100)),
                ('ProductName', models.CharField(blank=True, max_length=100, null=True)),
                ('Quantity', models.IntegerField(blank=True, null=True)),
                ('Price', models.IntegerField(blank=True, null=True)),
                ('Total_Price', models.IntegerField(blank=True, null=True)),
                ('Product_Image', models.ImageField(blank=True, null=True, upload_to='Cart_img')),
            ],
        ),
    ]
