# Generated by Django 6.0.1 on 2026-02-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pro_Name', models.CharField(max_length=100)),
                ('Pro_Category', models.CharField(max_length=100)),
                ('Pro_Prize', models.IntegerField()),
                ('Pro_Description', models.TextField()),
                ('Pro_Image', models.ImageField(upload_to='product')),
            ],
        ),
    ]
